pool: MyComputerAagent

variables:
  os: windows

steps:
  - script: 
     echo $(os)
  - script: 
     echo hello from script
    displayName: step1
  - script: 
     echo $(os)
    displayName: step2
  - script: 
     echo $(inputvar)
    displayName: step2